### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by L10N37** [rasky/mvs64#3]
I don't mean to come off as an A-hole, but can you please build these and upload them in releases? Someone has requested I put this on an SD card for him, and I owe the guy a favour. It's much easier to get your emulator out there for people to trial if they can just download a release. I will get the libdragon toolchain etc and build myself for now.

**Not everyone is this savvy, and a lot of people just want to wack this on an SD card and trial it on their system.

**Comment by rasky** [comment]
Upload what in releases, exactly? I can't upload commercial ROMs. There's really no shortcut here: you have to be able to build by yourself to test this emulator.
Also notice that it's still quite preliminary: don't expect many games to be playable.

**Comment by L10N37** [comment]
Sorry, hadn't looked into this properly and didn't fully understand.  I can see it's not a stand alone app yet with BIOS located by itself and creates stand alone game file.

Can you help with this?

No matter which BIOS is used, (being at this for ages) I get this error:

C:\Users\lfsan\mvs64>mingw32-make mvs64 BIOS=/games/uni-bios_2_3.rom ROM=games/mslug.zip
Building mvs64
make[1]: Entering directory 'C:/Users/lfsan/mvs64'
    [LD] mvsmakerom
    [CC] emu.c
make[1]: *** [C:/gcc-toolchain-mips64-win64/include/n64.mk:142: build/mvs64/emu.o] Error 1
make[1]: Leaving directory 'C:/Users/lfsan/mvs64'
mingw32-make: *** [Makefile:18: mvs64] Error 2



or

lfsan@GamingRig MINGW64 ~/mvs64 (main)
$ make mvs64 BIOS=/games/uni-bios_2_3.rom ROM=games/mslug2.zip V=1
Building mvs64
make[1]: Entering directory 'C:/Users/lfsan/mvs64'
    [LD] mvsmakerom
cc  -o mvsmakerom build/mvs64/mvsmakerom.o build/mvs64/miniz.o
    [CC] emu.c
C:/gcc-toolchain-mips64-win64/bin/mips64-elf-gcc -c -MMD      -Wno-unused-function -march=vr4300 -mtune=vr4300 -IC:/gcc-toolchain-mips64-win64/mips64-elf/include -falign-functions=32    -ffunction-sections -fdata-sections -g -ffile-prefix-map="C:/Users/lfsan/mvs64"= -DN64 -O2 -Wall -Werror -Wno-error=deprecated-declarations -fdiagnostics-color=always -std=gnu99 -o build/mvs64/emu.o emu.c

**Comment by L10N37** [comment]
I downloaded the older GCC toolchain v10.2.0 from Dec 2021.

C:\Users\lfsan\mvs64>mingw32-make mvs64 BIOS=/games/uni-bios_2_3.rom ROM=games/mslug.zip
Building mvs64
make[1]: Entering directory 'C:/Users/lfsan/mvs64'
    [LD] mvsmakerom
    [CC] emu.c
make[1]: *** [C:/gcc-toolchain-mips64-win64/include/n64.mk:142: build/mvs64/emu.o] Error 127
make[1]: Leaving directory 'C:/Users/lfsan/mvs64'
mingw32-make: *** [Makefile:18: mvs64] Error 2


The other error was happening with latest version V12.2.0 from Jan 16, 2023. 

It seemed to "do more" (i think) but still failed.

**just found 9.1.0 from July 2019 will try this (no luck)

Tried 11.3.0:

C:\Users\lfsan\mvs64>mingw32-make mvs64 BIOS=/games/uni-bios_2_3.rom ROM=games/mslug.zip
Building mvs64
mingw32-make: *** [Makefile:18: mvs64] Error -1073741790


***nevermind, i copy pasted the same thing over and over from notepad and missed the slash on the ROM file.
$ make mvs64 BIOS=/games/uni-bios_2_3.rom ROM=/games/mslug.zip
Building mvs64
make[1]: Entering directory 'C:/Users/lfsan/mvs64'
    [LD] mvsmakerom
    [CC] emu.c
In file included from emu.c:13:
platform.h:8:18: fatal error: libdragon.h: No such file or directory
    8 |         #include <libdragon.h>
      |                  ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [C:/gcc-toolchain-mips64-win64/include/n64.mk:142: build/mvs64/emu.o] Error 1
make[1]: Leaving directory 'C:/Users/lfsan/mvs64'
mingw32-make: *** [Makefile:18: mvs64] Error 2

I should be able to figure this out?
